### ISSUE TITLE
count_spe_trades is not defined

### ISSUE THREAD

**Issue by mg64ve** [5ymph0en1x/Heptet#2]
Hi @5ymph0en1x , I am getting this error:

```
p_value: 0.06075080504069065
Beta: [1.64576441]
Traceback (most recent call last):
  File "Trading_Model.py", line 250, in <module>
    EG_Test.process_trading(index=j, transaction_cost=0.000, **action_dict)
  File "/srv/STRATEGY/Cointegration.py", line 484, in process_trading
    self.gen_trade(order)
  File "/srv/STRATEGY/Cointegration.py", line 409, in gen_trade
    if self.count_spe_trades(instrument_1) < 0:
AttributeError: 'EGCointegration' object has no attribute 'count_spe_trades'
```

it seems function count_spe_trades is not defined.

**Comment by 5ymph0en1x** [comment]
Hello @mg64ve,
Sorry about the missing function.
I don't know how it happened but it should be ok now (see latest commit)...
Best regards
